const GET_ALL_DOGS = 'GET_ALL_DOGS';
const GET_DOG_DETAIL = 'GET_DOG_DETAIL';
const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS'
const FIND_DOG_NAME = 'FIND_DOG_NAME'
const FILTER_TEMPERAMENT = 'FILTER_TEMPERAMENT';
const CREATED_DOGS = 'CREATED_DOGS';
const CREATE_DOG = 'CREATE_DOG';
const CLEAN_DOG_DETAIL = 'CLEAN_DOG_DETAIL';
const ORDER_AZ = 'ORDER_AZ';
const ORDER_ZA = 'ORDER_ZA';
// const ORDER_WEIGHT_ASC = 'ORDER_WEIGHT_ASC';
// const ORDER_WEIGHT_DESC = 'ORDER_WEIGHT_DESC';
const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';
const DOGS_DB = 'DOGS_DB';
const DOGS_API = 'DOGS_API';
const FILTER_BY_TEMP = 'FILTER_BY_TEMP'
const SET_PAGE = 'SET_PAGE'

module.exports = {
  GET_ALL_DOGS,
  GET_DOG_DETAIL,
  GET_ALL_TEMPERAMENTS,
  FIND_DOG_NAME,
  FILTER_TEMPERAMENT,
  CREATE_DOG,
  CREATED_DOGS,
  CLEAN_DOG_DETAIL,
  ORDER_AZ,
  ORDER_ZA,
  ORDER_BY_WEIGHT,
  DOGS_DB,
  DOGS_API,
  FILTER_BY_TEMP,
  SET_PAGE
}